In [ ]:
#  Q1. Create a DataFrame with columns:
# Product, Price , Sales

import pandas as pd

dict = {
    "Product" : ["Laptop","Mouse","Keyboard","Headphone","Charger","Camera","Multiplug"],
    "Price" : [100000,500,1000,1500,800,25000,700],
    "Sales" : [2,4,6,9,8,3,5]
}

df =pd.DataFrame(dict)

print(df)

     Product   Price  Sales
0     Laptop  100000      2
1      Mouse     500      4
2   Keyboard    1000      6
3  Headphone    1500      9
4    Charger     800      8
5     Camera   25000      3
6  Multiplug     700      5

In [ ]:
# Q2. Add New Column

df["Revenue"] = df["Price"] * df["Sales"]

print(df)

     Product   Price  Sales  Revenue
0     Laptop  100000      2   200000
1      Mouse     500      4     2000
2   Keyboard    1000      6     6000
3  Headphone    1500      9    13500
4    Charger     800      8     6400
5     Camera   25000      3    75000
6  Multiplug     700      5     3500

In [ ]:
#Q3. Basic Operations

#Print first 3 rows

df.loc[0:2]

    Product   Price  Sales  Revenue
0    Laptop  100000      2   200000
1     Mouse     500      4     2000
2  Keyboard    1000      6     6000

In [ ]:
df.columns

Index(['Product', 'Price', 'Sales', 'Revenue'], dtype='object')

In [ ]:
df.dtypes

Product    object
Price       int64
Sales       int64
Revenue     int64
dtype: object

In [ ]:
# Q4. Add New Record - Add a new product using loc

df.loc[len(df)] = ["Watch",10000,8,10000*8]

print(df)

     Product   Price  Sales  Revenue
0     Laptop  100000      2   200000
1      Mouse     500      4     2000
2   Keyboard    1000      6     6000
3  Headphone    1500      9    13500
4    Charger     800      8     6400
5     Camera   25000      3    75000
6  Multiplug     700      5     3500
7      Watch   10000      8    80000

In [ ]:
# Q5. Mising Data Handling

df.loc[len(df)] = ["Table",10000,8,None]   # added missing values manually

print(df)

     Product   Price  Sales Revenue
0     Laptop  100000      2  200000
1      Mouse     500      4    2000
2   Keyboard    1000      6    6000
3  Headphone    1500      9   13500
4    Charger     800      8    6400
5     Camera   25000      3   75000
6  Multiplug     700      5    3500
7      Watch   10000      8   80000
8      Table   10000      8    None

In [ ]:
print(df.isnull())     # Detect using isnull()

   Product  Price  Sales  Revenue
0    False  False  False    False
1    False  False  False    False
2    False  False  False    False
3    False  False  False    False
4    False  False  False    False
5    False  False  False    False
6    False  False  False    False
7    False  False  False    False
8    False  False  False     True

In [56]:
print(df.isnull().sum()) # count missing values

Product    0
Price      0
Sales      0
Revenue    1
dtype: int64

In [57]:
df.fillna(0,inplace=True)   # fill using fillna(0)

print(df)

     Product   Price  Sales  Revenue
0     Laptop  100000      2   200000
1      Mouse     500      4     2000
2   Keyboard    1000      6     6000
3  Headphone    1500      9    13500
4    Charger     800      8     6400
5     Camera   25000      3    75000
6  Multiplug     700      5     3500
7      Watch   10000      8    80000
8      Table   10000      8        0

/tmp/ipykernel_7531/3512401540.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.fillna(0,inplace=True)   # fill using fillna(0)

In [59]:
# Q6. low Sales alert
# Display Product where Sales < 8

df[df["Sales"] < 8]

     Product   Price  Sales  Revenue
0     Laptop  100000      2   200000
1      Mouse     500      4     2000
2   Keyboard    1000      6     6000
5     Camera   25000      3    75000
6  Multiplug     700      5     3500